# Generated by Django 5.2 on 2025-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='PDF',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
