# Generated by Django 5.2 on 2025-05-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pdfdocument_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='savedHash',
            field=models.CharField(default='NULL'),
        ),
    ]
