# Generated by Django 5.2 on 2025-05-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pdfdocument_savedhash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='documentData',
            new_name='document_data',
        ),
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='savedHash',
            new_name='saved_hash',
        ),
        migrations.RenameField(
            model_name='textdocument',
            old_name='documentData',
            new_name='document_data',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='document_name',
            field=models.CharField(default='Empty'),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='document_name',
            field=models.CharField(default='Empty'),
        ),
    ]
