# Generated by Django 5.2 on 2025-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_documentdata_pdfdocument_document_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='saved_hash',
            field=models.CharField(default='NULL'),
        ),
    ]
